# Site settings
title: Anish Kumar
description: My Personal Website
#baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://anish52.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anish Kumar
user_description: Software development and data science is what keeps my adrenaline going; Can be often seen cursing the data. 2+years of experience as Machine Learning Engineer building data-driven solutions to increase efficiency and accuracy. Experienced at creating and maintaining ETL pipelines for predictive data modeling, data analysis, and visualization.
user_title: Connecting the dots.
email: ankumar@ucsd.edu
github_username:  https://github.com/anish52
linkedin_username:  https://www.linkedin.com/in/anishkr-10052bitm/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
